services:
  mapproxy:
    build: .
    ports:
      - "8000:8000"
    environment:
      UWSGI_HTTP: "0.0.0.0:8000"
      UWSGI_MASTER: 1
      UWSGI_PROCESSES: 4
      OS_URL: "${OS_URL:-t1.acc.data.amsterdam.nl}" # Acceptance Tiles as default
      MAPSERVER_URL: "${MAPSERVER_URL:-map.data-o.azure.amsterdam.nl}"
