services:
  mapproxy:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAPSERVER_URL: "https://map.data-o.azure.amsterdam.nl" # dev mapserver; prd uses the Dockerfile default
    ports:
      - "8000:8000"
    environment:
      UWSGI_HTTP: "0.0.0.0:8000"
      UWSGI_MASTER: 1
      UWSGI_PROCESSES: 4
      OS_URL: "${OS_URL:-t1.acc.data.amsterdam.nl}" # Acceptance Tiles as default
      APPLICATIONINSIGHTS_INSTRUMENTATION_KEY: ""