services:
  topo_rd:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAPSERVER_URL: "${MAPSERVER_URL:-map.data-t.azure.amsterdam.nl/tiled}"
    command: >
      mapproxy-seed -c 1 -s /app/seed.yaml -f /app/mapproxy-seed.yaml --seed=topo_rd_kbk,topo_rd_bgt
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "${AZURE_STORAGE_CONNECTION_STRING}"

  topo_rd_light:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAPSERVER_URL: "${MAPSERVER_URL:-map.data-t.azure.amsterdam.nl/tiled}"
    command: >
      mapproxy-seed -c 1 -s /app/seed.yaml -f /app/mapproxy-seed.yaml --seed=topo_rd_light_kbk,topo_rd_light_bgt
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "${AZURE_STORAGE_CONNECTION_STRING}"

  topo_rd_zw:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAPSERVER_URL: "${MAPSERVER_URL:-map.data-t.azure.amsterdam.nl/tiled}"
    command: >
      mapproxy-seed -1 2 -s /app/seed.yaml -f /app/mapproxy-seed.yaml --seed=topo_rd_zw_kbk,topo_rd_zw_bgt
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "${AZURE_STORAGE_CONNECTION_STRING}"

  topo_wm:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAPSERVER_URL: "${MAPSERVER_URL:-map.data-t.azure.amsterdam.nl/tiled}"
    command: >
      mapproxy-seed -c 1 -s /app/seed.yaml -f /app/mapproxy-seed.yaml --seed=topo_wm_kbk,topo_wm_bgt
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "${AZURE_STORAGE_CONNECTION_STRING}"

  topo_wm_light:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAPSERVER_URL: "${MAPSERVER_URL:-map.data-t.azure.amsterdam.nl/tiled}"
    command: >
      mapproxy-seed -c 1 -s /app/seed.yaml -f /app/mapproxy-seed.yaml --seed=topo_wm_light_kbk,topo_wm_light_bgt
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "${AZURE_STORAGE_CONNECTION_STRING}"

  topo_wm_zw:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAPSERVER_URL: "${MAPSERVER_URL:-map.data-t.azure.amsterdam.nl/tiled}"
    command: >
      mapproxy-seed -c 1 -s /app/seed.yaml -f /app/mapproxy-seed.yaml --seed=topo_wm_zw_kbk,topo_wm_zw_bgt
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "${AZURE_STORAGE_CONNECTION_STRING}"

  topo_rd_lufo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAPSERVER_URL: "${MAPSERVER_URL:-map.data-t.azure.amsterdam.nl/tiled}"
    user: root
    command: >
      mapproxy-seed -c 1 -s /app/seed.yaml -f /app/mapproxy-seed.yaml --seed=lufo_rd
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "${AZURE_STORAGE_CONNECTION_STRING}"

  topo_wm_lufo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAPSERVER_URL: "${MAPSERVER_URL:-map.data-t.azure.amsterdam.nl/tiled}"
    user: root
    command: >
      mapproxy-seed -c 4 -s /app/seed.yaml -f /app/mapproxy-seed.yaml --seed=lufo_wm
    environment:
      AZURE_STORAGE_CONNECTION_STRING: "${AZURE_STORAGE_CONNECTION_STRING}"
