topo-rd:
  build: .
  command: mapproxy-seed -c 6 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=topo_rd_kbk,topo_rd_bgt
  volumes:
    - "/mnt/tiles:/mnt/tiles"

topo-rd-light:
  build: .
  command: mapproxy-seed -c 6 -s /app/seed.yaml -f /app/mapproxy.yaml --seed= topo_rd_light_kbk, topo_rd_light_bgt
  volumes:
    - "/mnt/tiles:/mnt/tiles"

topo-rd-zw:
  build: .
  command: mapproxy-seed -c 6 -s /app/seed.yaml -f /app/mapproxy.yaml --seed= topo_rd_zw_kbk, topo_rd_zw_bgt
  volumes:
    - "/mnt/tiles:/mnt/tiles"

topo-wm:
  build: .
  command: mapproxy-seed -c 10 -s /app/seed.yaml -f /app/mapproxy.yaml --seed= topo_wm_kbk, topo_wm_bgt
  volumes:
    - "/mnt/tiles:/mnt/tiles"

topo-wm-light:
  build: .
  command: mapproxy-seed -c 10 -s /app/seed.yaml -f /app/mapproxy.yaml --seed= topo_wm_light_kbk, topo_wm_light_bgt
  volumes:
    - "/mnt/tiles:/mnt/tiles"

topo-wm-zw:
  build: .
  command: mapproxy-seed -c 10 -s /app/seed.yaml -f /app/mapproxy.yaml --seed= topo_wm_zw_kbk, topo_wm_zw_bgt
  volumes:
    - "/mnt/tiles:/mnt/tiles"

topo-lufo:
  build: .
  command: seed-lufo.sh
  volumes:
    - "/mnt/tiles:/mnt/tiles"


