version: '3.0'
services:
  mapproxy:
    build: .
    ports:
      - "8000:8000"
    environment:
      UWSGI_HTTP: "0.0.0.0:8000"
      UWSGI_MASTER: 1
      UWSGI_PROCESSES: 4
      OS_URL: "e4b811595a6f4b4aac96f600b037d3dd.objectstore.eu" # Acceptance Tiles as default

  mapserver:
    image: docker-registry.data.amsterdam.nl/datapunt/mapserver-tiles:2
    user: root
    environment:
      MAP_URL: "http://mapserver"
      LEGEND_URL: "http://mapserver"

  topo_rd:
    build: .
    user: root
    links:
      - mapserver
      - database
    command: >
      mapproxy-seed -c 1 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=topo_rd_kbk,topo_rd_bgt
    volumes:
      - "/mnt/tiles:/mnt/tiles"

  topo_rd_light:
    build: .
    user: root
    links:
      - mapserver
      - database
    command: >
      mapproxy-seed -c 1 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=topo_rd_light_kbk,topo_rd_light_bgt
    volumes:
      - "/mnt/tiles:/mnt/tiles"

  topo_rd_zw:
    build: .
    user: root
    links:
      - mapserver
      - database
    command: >
      mapproxy-seed -1 2 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=topo_rd_zw_kbk,topo_rd_zw_bgt
    volumes:
      - "/mnt/tiles:/mnt/tiles"

  topo_wm:
    build: .
    user: root
    links:
      - mapserver
      - database
    command: >
      mapproxy-seed -c 1 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=topo_wm_kbk,topo_wm_bgt
    volumes:
      - "/mnt/tiles:/mnt/tiles"

  topo_wm_light:
    build: .
    user: root
    links:
      - mapserver
      - database
    command: >
      mapproxy-seed -c 1 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=topo_wm_light_kbk,topo_wm_light_bgt
    volumes:
      - "/mnt/tiles:/mnt/tiles"

  topo_wm_zw:
    build: .
    user: root
    links:
      - mapserver
      - database
    command: >
      mapproxy-seed -c 1 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=topo_wm_zw_kbk,topo_wm_zw_bgt
    volumes:
      - "/mnt/tiles:/mnt/tiles"

  topo-lufo:
    build: .
    user: root
    command: >
      mapproxy-seed -c 1 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=lufo_rd
    volumes:
      - "/mnt/tiles:/mnt/tiles"

  topo-lufo-wm:
    build: .
    user: root
    command: >
      mapproxy-seed -c 4 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=lufo_wm
    volumes:
      - "/mnt/tiles:/mnt/tiles"
