topo-kbk:
  build: .
  command: seed-kbk.sh
  volumes:
    - "/mnt/tiles:/mnt/tiles"

topo-bgt:
  build: .
  command: seed-bgt.sh
  volumes:
    - "/mnt/tiles:/mnt/tiles"

topo-google:
  build: .
  command: seed-google.sh
  volumes:
    - "/mnt/tiles:/mnt/tiles"

