version: '3.0'
services:
  mapproxy:
#    image: build.datapunt.amsterdam.nl:5000/datapunt/mapproxy
    build: src
    ports:
      - "8000:8000"
    environment:
      - UWSGI_HTTP=0.0.0.0:8000
      - UWSGI_MASTER=1
      - UWSGI_PROCESSES=4

  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/postgres
    environment:
      POSTGRES_PASSWORD: insecure
      POSTGRES_USER: postgres

  mapserver:
    image: build.datapunt.amsterdam.nl:5000/datapunt/mapserver-private
    user: root
    environment:
      ATLAS_DB_HOST: database
      ATLAS_DB_PORT: 5432

      BASISKAART_DB_HOST: database
      BASISKAART_DB_PORT: 5432

  topo_rd:
    build: src
    user: root
    links:
      - mapserver
      - database
    command: >
      mapproxy-seed -c 6 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=topo_rd_kbk,topo_rd_bgt
    volumes:
      - "/mnt/tiles:/mnt/tiles"

  topo_rd_light:
    build: src
    user: root
    links:
      - mapserver
      - database
    command: >
      mapproxy-seed -c 6 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=topo_rd_light_kbk,topo_rd_light_bgt
    volumes:
      - "/mnt/tiles:/mnt/tiles"

  topo_rd_zw:
    build: src
    user: root
    links:
      - mapserver
      - database
    command: >
      mapproxy-seed -c 6 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=topo_rd_zw_kbk,topo_rd_zw_bgt
    volumes:
      - "/mnt/tiles:/mnt/tiles"

  topo_wm:
    build: src
    user: root
    links:
      - mapserver
      - database
    command: >
      mapproxy-seed -c 6 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=topo_wm_kbk,topo_wm_bgt
    volumes:
      - "/mnt/tiles:/mnt/tiles"

  topo_wm_light:
    build: src
    user: root
    links:
      - mapserver
      - database
    command: >
      mapproxy-seed -c 6 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=topo_wm_light_kbk,topo_wm_light_bgt
    volumes:
      - "/mnt/tiles:/mnt/tiles"

  topo_wm_zw:
    build: src
    user: root
    links:
      - mapserver
      - database
    command: >
      mapproxy-seed -c 6 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=topo_wm_zw_kbk,topo_wm_zw_bgt
    volumes:
      - "/mnt/tiles:/mnt/tiles"

  topo-lufo:
    build: src
    user: root
    command: seed-lufo.sh
    volumes:
      - "/mnt/tiles:/mnt/tiles"


