version: '3.0'
services:
  mapproxy:
    build: .
    ports:
      - "8000:8000"
    environment:
      UWSGI_HTTP: "0.0.0.0:8000"
      UWSGI_MASTER: 1
      UWSGI_PROCESSES: 4
      OS_URL: "dpbk-o-bhbuh2chc3evemgn.a01.azurefd.net" # Acceptance Tiles as default
