version: '2.1'
services:
  upload:
#    build: ../../
    image: build.datapunt.amsterdam.nl:5000/datapunt/tileupload:${ENVIRONMENT}
    volumes:
      - ${SOURCE_PATH}:/app/data
    environment:
      - OS_CONTAINER=${OS_CONTAINER}
      - OS_USERNAME=${OS_USERNAME}
      - OS_PROJECT_NAME=${OS_PROJECT_NAME}
      - OS_TENANT_NAME=${OS_TENANT_NAME}
      - OS_AUTH_TYPE=password
      - OS_AUTH_URL=https://identity.stack.cloudvps.com/v2.0
      - OS_PASSWORD=${OS_PASSWORD}
    mem_limit: 14g
    command: >
      bash -c "cd /app/data/${OS_CONTAINER} && swift -s -v --info upload --object-threads 10 ${OS_CONTAINER} ."
