version: '2.1'
services:
  upload:
#    build: ../../
    image: build.datapunt.amsterdam.nl:5000/datapunt/tileupload:${ENVIRONMENT}
    volumes:
      - ${SOURCE_PATH}:/app/data
    environment:
      - OS_PASSWORD=${OS_PASSWORD}
      - OS_CONTAINER=${OS_CONTAINER}
      - OS_USERNAME=${OS_USERNAME}
      - OS_TENANT_NAME=${OS_TENANT_NAME}
      - OS_TENANT_ID=${OS_TENANT_ID}
      - SOURCE_PATH=${SOURCE_PATH}
      - DEBUG=${DEBUG}
      - PROGRESS=${PROGRESS}
      - NR_OF_PROCESSES=${NR_OF_PROCESSES}
    command: >
      bash -c "python3 ./import_raket.py"

