version: '2.1'
services:
  upload:
#    build: ../../
    image: build.datapunt.amsterdam.nl:5000/datapunt/tileupload:${ENVIRONMENT}
    volumes:
      - ${SOURCE_PATH}:/app/data
    environment:
      - OBJECTSTORE_PASSWORD=${OBJECTSTORE_PASSWORD}
      - OBJECTSTORE_CONTAINER=${OBJECTSTORE_CONTAINER}
      - OBJECTSTORE_USER=${OBJECTSTORE_USER}
      - OBJECTSTORE_TENANT_NAME=${OBJECTSTORE_TENANT_NAME}
      - OBJECTSTORE_TENANT_ID=${OBJECTSTORE_TENANT_ID}
      - SOURCE_PATH=${SOURCE_PATH}
      - PROGRESS=${PROGRESS}
      - NR_OF_PROCESSES=${NR_OF_PROCESSES}
    command: >
      bash -c "python3 ./import_raket.py"
