services:
  demo:
  tms:
    # needs no arguments
  wms:
    srs: ['EPSG:4326', 'EPSG:900913', 'EPSG:3857', 'EPSG:28992']
    md:
      # metadata used in capabilities documents
      title: MapProxy Amsterdam
      abstract: MapProxy configuratie voor Amsterdam
      online_resource: http://mapproxy.org/
      contact:
        person: Datapunt
        position: n/a
        organization: Gemeente Amsterdam
        address: n/a
        city: Amsterdam
        postcode: n/a
        country: Netherlands
        phone: n/a
        fax: n/a
        email: datapunt@amsterdam.nl
      fees: 'None'

layers:
  - name: topografie
    title: topografie
    md:
      abstract: Basiskaart Amsterdam
    sources: [topo_rd_tiled]
    min_res: 3440.64
    layers:
      - name: basiskaart
        title: basiskaart
        md:
          abstract: Basiskaart Amsterdam
        layers:
          - name: bgt
            title: bgt
            sources: [topo_rd_tiled]
            min_res: 0.84
          - name: kbk10
            title: kbk10
            sources: [topo_rd_tiled]
            min_res: 1.68
            max_res: 0.84
          - name: kbk50
            title: kbk50
            sources: [topo_rd_tiled]
            min_res: 3440.64
            max_res: 1.68
      - name: basiskaart-light
        title: basiskaart-light
        md:
          abstract: Basiskaart Amsterdam - Light
        layers:
          - name: bgt-light
            title: bgt-light
            sources: [topo_rd_light_tiled]
            min_res: 0.84
          - name: kbk10-light
            title: kbk10-light
            sources: [topo_rd_light_tiled]
            min_res: 1.68
            max_res: 0.84
          - name: kbk50-light
            title: kbk50-light
            sources: [topo_rd_light_tiled]
            min_res: 3440.64
            max_res: 1.68
      - name: basiskaart-zwartwit
        title: basiskaart-zwartwit
        md:
          abstract: Basiskaart Amsterdam - ZW
        layers:
          - name: bgt-zwartwit
            title: bgt-zwartwit
            sources: [topo_rd_zw_tiled]
            min_res: 0.84
          - name: kbk10-zwartwit
            title: kbk10-zwartwit
            sources: [topo_rd_zw_tiled]
            min_res: 1.68
            max_res: 0.84
          - name: kbk50-zwartwit
            title: kbk50-zwartwit
            sources: [topo_rd_zw_tiled]
            min_res: 3440.64
            max_res: 1.68
  - name: topo_rd
    title: Topo RD
    sources: [topo_rd_cache]
  - name: topo_wm
    title: Topo Webmercator
    sources: [topo_wm_cache]
  - name: lufo_RD
    title: Luchtfoto RD
    sources: [lufo_rd_cache]

caches:
#### TOPO RD - KBK & BGT - Standaard kleur
  topo_rd_cache:
    grids: [nl_grid]
    sources: [topografie]
    cache_dir: /mnt/tiles
    cache:
      type: file
      directory_layout: tms

  topo_rd_tiled:
    grids: [nl_grid]
    sources: [topografie_rd_tiles]

#### TOPO RD - KBK & BGT - Light kleur
  topo_rd_light_cache:
    grids: [nl_grid]
    sources: [topografie_light]
    cache_dir: /mnt/tiles
    cache:
      type: file
      directory_layout: tms

  topo_rd_light_tiled:
    grids: [nl_grid]
    sources: [topografie_rd_light_tiles]

  #### TOPO RD - KBK & BGT - Zwartwit
  topo_rd_zw_cache:
    grids: [nl_grid]
    sources: [topografie_zw]
    cache_dir: /mnt/tiles
    cache:
      type: file
      directory_layout: tms

  topo_rd_zw_tiled:
    grids: [nl_grid]
    sources: [topografie_rd_zw_tiles]

#### TOPO Webmercator (wm) - KBK & BGT - Standaard kleur
  topo_wm_cache:
    grids: [webmercator]
    sources: [topografie_wm]
    cache_dir: /mnt/tiles
    cache:
      type: file
      directory_layout: tms

#### TOPO wm - KBK & BGT - Light kleur
  topo_wm_light_cache:
    grids: [webmercator]
    sources: [topografie_wm_light]
    cache_dir: /mnt/tiles
    cache:
      type: file
      directory_layout: tms

 ### TOPO Webmercator (wm) - KBK & BGT - Zwartwit
  topo_wm_zw_cache:
    grids: [webmercator]
    sources: [topografie_wm_zw]
    cache_dir: /mnt/tiles
    cache:
      type: file
      directory_layout: tms

# Luchtfoto's
  lufo_rd_cache:
    grids: [nl_grid]
    sources: [lufo_wms]
    cache_dir: /mnt/tiles
    format: image/jpeg
    cache:
      type: file
      directory_layout: tms

sources:
# basiskaart standaard kleur
  topografie:
    type: wms
    req:
      url: http://mapserver/maps/topografie
      layers: basiskaart
    seed_only: true

 # basiskaart light kleur
  topografie_light:
    type: wms
    req:
      url: http://mapserver/maps/topografie
      layers: basiskaart-light
    seed_only: true

# basiskaart zwartwit kleur
  topografie_zwartwit:
    type: wms
    req:
      url: http://mapserver/maps/topografie
      layers: basiskaart-zwartwit
    seed_only: true

# basiskaart webmercator (wm)
  topografie_wm:
    type: wms
    req:
      url: http://mapserver/maps/topografie_wm
      layers: basiskaart
    seed_only: true

# basiskaart wm light
  topografie_wm_light:
    type: wms
    req:
      url: http://mapserver/maps/topografie_wm
      layers: basiskaart-light
    seed_only: true

# basiskaart wm zwartwit
  topografie_wm_zw:
    type: wms
    req:
      url: http://mapserver/maps/topografie_wm
      layers: basiskaart-zwartwit
    seed_only: true

# Use tile cache as a source for WMS
  topografie_rd_tiles:
    type: tile
    grid: nl_grid
    url: http://a53b807905f74d39ae9745d6d003854a.objectstore.eu/topo_rd_cache_EPSG28992/%(z)s/%(x)s/%(y)s.png
  topografie_rd_light_tiles:
    type: tile
    grid: nl_grid
    url: http://a53b807905f74d39ae9745d6d003854a.objectstore.eu/topo_rd_light_cache_EPSG28992/%(z)s/%(x)s/%(y)s.png
  topografie_rd_zw_tiles:
    type: tile
    grid: nl_grid
    url: http://a53b807905f74d39ae9745d6d003854a.objectstore.eu/topo_rd_zw_cache_EPSG28992/%(z)s/%(x)s/%(y)s.png

# Example to tile to locally with the mapserver docker also running:
  lufo_wms:
    type: wms
    req:
      url: http://172.17.0.1:32770/maps/lufo
      layers: lufo-TILE

grids:
  nl_grid:
    srs: EPSG:28992
    tile_size: [256,256]
    res: [3440.64,1720.32,860.16,430.08,215.04,107.52,53.76,26.88,13.44,6.72,3.36,1.68,0.84,0.42,0.21,0.105,0.0525]
    #     0       1       2      3      4      5      6     7     8     9    10   11   12   13   14   15    16
    bbox: [-285401.920,22598.080,595401.9199999999,903401.9199999999]

  webmercator:
    base: GLOBAL_WEBMERCATOR
    num_levels: 22

globals:
  cache:
    base_dir: '/app'
    lock_dir: '/app'
    tile_lock_dir: '/app'
    meta_size: [4, 4]
    meta_buffer: 128
  http:
    ssl_no_cert_checks: True

  image:
      resampling_method: bicubic
