services:
  demo:
  tms:
    # needs no arguments
  wms:
    srs: ['EPSG:4326', 'EPSG:900913', 'EPSG:3857', 'EPSG:28992']
    md:
      # metadata used in capabilities documents
      title: MapProxy Amsterdam
      abstract: MapProxy configuratie voor Amsterdam
      online_resource: http://mapproxy.org/
      contact:
        person: Datapunt
        position: n/a
        organization: Gemeente Amsterdam
        address: n/a
        city: Amsterdam
        postcode: n/a
        country: Netherlands
        phone: n/a
        fax: n/a
        email: datapunt.ois@amsterdam.nl
      fees: 'None'

layers:
  - name: topo_rd
    title: Topo RD
    sources: [topo_rd_cache]
  - name: topo_google
    title: Topo Google
    sources: [topo_google_cache]
  - name: lufo_RD
    title: Luchtfoto RD
    sources: [lufo_rd_cache]

caches:
  topo_rd_cache:
    grids: [nl_grid]
    sources: [diva_wms, datapunt_wms_kbk10, datapunt_wms_kbk50]
    cache:
      type: file
      directory_layout: tms
      
  topo_google_cache:
    grids: [webmercator]
#    sources: [diva_wms, datapunt_wms_kbk10, datapunt_wms_kbk50]
    sources: [dp_basiskaart_bgt, dp_basiskaart_kbk10, dp_basiskaart_kbk50, dp_basiskaart_light_bgt, dp_basiskaart_light_kbk10, dp_basiskaart_light_kbk50, dp_basiskaart_zw_bgt, dp_basiskaart_zw_kbk10, dp_basiskaart_zw_kbk50]
    cache:
      type: file
      directory_layout: tms
      
  lufo_rd_cache:
    grids: [nl_grid]
    sources: [lufo_wms]
    format: image/jpeg
    cache:
      type: file
      directory_layout: tms

sources:
  dp_basiskaart_bgt:
    type: wms
    req:
      url: http://map-acc.data.amsterdam.nl/maps/topografie
      layers: basiskaart
    min_res: 0.84
  dp_basiskaart_kbk10:
  type: wms
     req:
       url: https://map-acc.datapunt.amsterdam.nl/maps/kbk10
       layers: basiskaart
     min_res: 3.36
     max_res: 0.85
  dp_basiskaart_kbk50:
    type: wms
      req:
        url: https://map-acc.datapunt.amsterdam.nl/maps/kbk50
        layers: basiskaart
      min_res: 3440.64
      max_res: 3.37
  dp_basiskaart_light_bgt:
  type: wms
      req:
        url: http://map-acc.data.amsterdam.nl/maps/topografie
        layers: basiskaart-light
      min_res: 0.84
  dp_basiskaart_light_kbk10:
   type: wms
       req:
         url: https://map-acc.datapunt.amsterdam.nl/maps/kbk10
         layers: basiskaart-light
       min_res: 3.36
       max_res: 0.85
  dp_basiskaart_light_kbk50:
  type: wms
        req:
          url: https://map-acc.datapunt.amsterdam.nl/maps/kbk50
          layers: basiskaart-light
        min_res: 3440.64
        max_res: 3.37
  dp_basiskaart_zw_bgt:
   type: wms
       req:
         url: http://map-acc.data.amsterdam.nl/maps/topografie
         layers: basiskaart-zwartwit
       min_res: 0.84
  dp_basiskaart_zw_kbk10:
  type: wms
       req:
         url: https://map-acc.datapunt.amsterdam.nl/maps/kbk10
         layers: basiskaart-zwartwit
       min_res: 3.36
       max_res: 0.85
  dp_basiskaart_zw_kbk50:
type: wms
      req:
        url: https://map-acc.datapunt.amsterdam.nl/maps/kbk50
        layers: basiskaart-zwartwit
      min_res: 3440.64
      max_res: 3.37

#  datapunt_wms_bgt:
#    type: wms
#    req:
#      url: https://map-acc.datapunt.amsterdam.nl/maps/bgt
#      layers: vlakken,lijnen,teksten

# Example to tile to locally with the mapserver docker also running:
  lufo_wms:
    type: wms
    req:
      url: http://172.17.0.1:32770/maps/lufo
      layers: lufo-TILE
# Example to tile again the Acceptance environment:

grids:
  nl_grid:
    srs: EPSG:28992
    tile_size: [256,256]
    res: [3440.64,1720.32,860.16,430.08,215.04,107.52,53.76,26.88,13.44,6.72,3.36,1.68,0.84,0.42,0.21,0.105,0.0525]
    #     0       1       2      3      4      5      6     7     8     9    10   11   12   13   14   15    16
    bbox: [-285401.920,22598.080,595401.9199999999,903401.9199999999]

  webmercator:
    base: GLOBAL_WEBMERCATOR
    num_levels: 22

globals:
  cache:
    base_dir: '/mnt/tiles'
    lock_dir: '/mnt/tiles'
    tile_lock_dir: '/mnt/tiles'
    meta_size: [4, 4]
    meta_buffer: 128
  http:
    ssl_no_cert_checks: True

  image:
      resampling_method: bicubic

